[package]

name = "syslog"
version = "3.0.0"
authors = [ "contact@geoffroycouprie.com" ]
description = "Send log messages to syslog"
license = "MIT"
repository = "https://github.com/Geal/rust-syslog"
documentation = "http://rust.unhandledexpression.com/syslog/"
keywords = ["syslog", "logs", "logging"]

[dependencies]
unix_socket = "~0.4.4"
libc        = "~0.1"
time        = "~0.1"
log         = "~0.3.1"

[features]
nightly = []
