[package]

name = "syslog"
version = "5.0.0"
authors = [ "contact@geoffroycouprie.com" ]
description = "Send log messages to syslog"
license = "MIT"
repository = "https://github.com/Geal/rust-syslog"
documentation = "https://docs.rs/syslog"
keywords = ["syslog", "logs", "logging"]

[dependencies]
libc        = "0.2.67"
time        = "0.1.42"
log         = { version = "0.4.8", features = [ "std" ] }
error-chain = { version = "0.12.2", default-features = false }

[features]
nightly = []
backtrace = ["error-chain/backtrace"]
